DROP TABLE IF EXISTS promotion;

CREATE TABLE promotion (
  	PRODUCTID VARCHAR(50) NOT NULL PRIMARY KEY,
PROMOTIONNAME VARCHAR(50) NOT NULL,
STARTDATE Date DEFAULT NULL,
ENDDATE DATE DEFAULT NULL,
DISCOUNTTYPE VARCHAR2(50),
STATUS CHAR(1) DEFAULT 'Y'
);